# Generated by Django 4.0.4 on 2022-05-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='imgp',
            field=models.FileField(blank=True, null=True, upload_to='imgs', verbose_name='user_img'),
        ),
    ]
