# Generated by Django 4.0.4 on 2022-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0002_alter_user1_imgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
    ]
