# Generated by Django 4.0.4 on 2022-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0003_user1_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='timestamp'),
        ),
    ]
