# Generated by Django 4.0.4 on 2022-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0004_user1_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='pan_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone_no'),
        ),
    ]
