# Generated by Django 4.0.4 on 2022-05-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0005_user1_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='pan_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='PAN_no'),
        ),
    ]
