# Generated by Django 4.0.4 on 2022-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0006_alter_user1_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='digi_pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='PIN'),
        ),
    ]
