# Generated by Django 4.0.4 on 2022-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0008_remove_user1_digi_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN_no'),
        ),
    ]
