# Generated by Django 4.0.4 on 2022-05-23 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0012_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_symbol', models.CharField(max_length=60)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('product', models.CharField(max_length=30)),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
