# Generated by Django 4.0.4 on 2022-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oerder_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='share_symbol',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
