# Generated by Django 4.0.4 on 2022-05-23 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0015_order_share_deal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_symbol', models.CharField(blank=True, max_length=60, null=True)),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
