# Generated by Django 4.0.4 on 2022-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0016_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
