# Generated by Django 4.0.4 on 2022-05-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0017_holdings_avg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
