# Generated by Django 4.0.4 on 2022-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapi', '0018_alter_holdings_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='avg_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
